version: '3.3'

services:
  db:
    image: postgres:13-alpine
    container_name: is_lab1_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./is_lab1
      args:
        ADMIN_NAME: ${ADMIN_NAME}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    container_name: is_lab1_app
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "55080:8080"
      - "55990:9990"
    depends_on:
      - db

volumes:
  postgres_data:
